services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    admin.csv_file_importer.users:
            class: AdminBundle\Service\CSVImporters\UserCSVFileImporter
            arguments: ["@doctrine"]
